### ISSUE TITLE
Dictionary list broken in firefox 17

### ISSUE THREAD

**Issue by saraedum** [saraedum/switchasitype#3]
The extension is currently broken: https://bugzilla.mozilla.org/show_bug.cgi?id=843727

There is not much one can do about in this extension.

**Comment by renatosilva** [comment]
The addon works partially in Firefox 43. It changes the language of this text when moving the cursor, and it does not work in Gmail at all.

**Comment by saraedum** [comment]
@renatosilva Please create a new issue for this.
